# EntityCount
# Count entities in a world
# This file must contain valid YAML code. A YAML checker may be found at http://www.yamllint.com
#
# Design: SlimeDog
# Implementation: drives_a_ford
# Testing: SlimeDog
#
# Supported MC versions:
# https://github.com/SlimeDog/EntityCount#readme
# Default configuration:
# https://github.com/SlimeDog/EntityCount/blob/master/src/main/resources/config.yml
#

# ========== CHECK FOR UPDATES =====================================================================
# If you do not want notification of available updates in the console log, you may disable it here.
check-for-updates: true
# Update source may be either Hangar (default) or SpigotMC.
update-source: Hangar

# ========== BSTATS METRICS ========================================================================
# By default, the plugin collects and transmits anonymous statistics to bstats.org.
# Data collection may be disabled here, or generally in the bStats/config.yml.
#
enable-metrics: true
