name: ${project.name}
version: ${project.version}
api-version: 1.13
main: ${project.groupId}.${project.artifactId}.${project.name}
description: ${project.description}
authors: [drives_a_ford, SlimeDog]
folia-supported: true

commands:
  entitycount:
    description: Counts entities in a world
    usage: /<command> [ <world> ] [ <entity-type> ]
    aliases: [ec]
    permission: entitycount.use

permissions:
  entitycount.use:
    description: Allows using the entitycount parent command
    default: op
  entitycount.use.count:
    description: Allows counting of entities
    default: op
    children:
      entitycount.use: true
  entitycount.use.reload:
    description: Allows reloading the plugin / messages
    default: op
    children:
      entitycount.use: true
